import { Grades } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime';

export const gradesSeeds: Grades[] = [
  {
    id: 1,
    subject_id: 1,
    course_id: 1,
    student_id: 1,
    teacher_id: 1,
    semester: 1,
    first_grade: new Decimal(10),
    second_grade: new Decimal(5),
    extra_grade: new Decimal(4),
    final_grade: new Decimal(1),
    situation: 'APPROVED',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    subject_id: 2,
    course_id: 2,
    student_id: 2,
    teacher_id: 2,
    semester: 2,
    first_grade: new Decimal(3),
    second_grade: new Decimal(5),
    extra_grade: new Decimal(2),
    final_grade: new Decimal(1),
    situation: 'REPROVED',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    subject_id: 3,
    course_id: 3,
    student_id: 3,
    teacher_id: 3,
    semester: 3,
    first_grade: new Decimal(5),
    second_grade: new Decimal(5),
    extra_grade: new Decimal(9),
    final_grade: new Decimal(7),
    situation: 'APPROVED',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    subject_id: 4,
    course_id: 4,
    student_id: 4,
    teacher_id: 4,
    semester: 4,
    first_grade: new Decimal(10),
    second_grade: new Decimal(10),
    extra_grade: new Decimal(9),
    final_grade: new Decimal(7),
    situation: 'APPROVED',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 5,
    subject_id: 5,
    course_id: 5,
    student_id: 5,
    teacher_id: 3,
    semester: 6,
    first_grade: new Decimal(1),
    second_grade: new Decimal(10),
    extra_grade: new Decimal(10),
    final_grade: new Decimal(8),
    situation: 'APPROVED',
    created_at: new Date(),
    updated_at: new Date(),
  },
];
