import { Permissions } from '@prisma/client';

export const permissionsSeeds: Permissions[] = [
  // USERS RESOURCE
  {
    id: 1,
    user_role: 'ADMIN',
    system_resource_id: 1,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    user_role: 'USER',
    system_resource_id: 1,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    user_role: 'STUDENT',
    system_resource_id: 1,
    can_create: false,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    user_role: 'TEACHER',
    system_resource_id: 1,
    can_create: false,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // STUDENTS RESOURCE
  {
    id: 5,
    user_role: 'ADMIN',
    system_resource_id: 2,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    user_role: 'USER',
    system_resource_id: 2,
    can_create: true,
    can_read: false,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 7,
    user_role: 'STUDENT',
    system_resource_id: 2,
    can_create: false,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    user_role: 'TEACHER',
    system_resource_id: 2,
    can_create: false,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // TEACHERS RESOURCE
  {
    id: 9,
    user_role: 'ADMIN',
    system_resource_id: 3,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    user_role: 'USER',
    system_resource_id: 3,
    can_create: true,
    can_read: false,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 11,
    user_role: 'STUDENT',
    system_resource_id: 3,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 12,
    user_role: 'TEACHER',
    system_resource_id: 3,
    can_create: false,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // COURSES CATEGORIES RESOURCE
  {
    id: 13,
    user_role: 'ADMIN',
    system_resource_id: 4,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 14,
    user_role: 'USER',
    system_resource_id: 4,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 15,
    user_role: 'STUDENT',
    system_resource_id: 4,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 16,
    user_role: 'TEACHER',
    system_resource_id: 4,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // COURSES RESOURCES
  {
    id: 17,
    user_role: 'ADMIN',
    system_resource_id: 5,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 18,
    user_role: 'USER',
    system_resource_id: 5,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 19,
    user_role: 'STUDENT',
    system_resource_id: 5,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 20,
    user_role: 'TEACHER',
    system_resource_id: 5,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // SUBJECTS RESOURCES
  {
    id: 21,
    user_role: 'ADMIN',
    system_resource_id: 6,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 22,
    user_role: 'USER',
    system_resource_id: 6,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 23,
    user_role: 'STUDENT',
    system_resource_id: 6,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 24,
    user_role: 'TEACHER',
    system_resource_id: 6,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // COURSES SUBJECTS RESOURCE
  {
    id: 25,
    user_role: 'ADMIN',
    system_resource_id: 7,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 26,
    user_role: 'USER',
    system_resource_id: 7,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 27,
    user_role: 'STUDENT',
    system_resource_id: 7,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 28,
    user_role: 'TEACHER',
    system_resource_id: 7,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // TEACHERS SUBJECTS
  {
    id: 29,
    user_role: 'ADMIN',
    system_resource_id: 8,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 30,
    user_role: 'USER',
    system_resource_id: 8,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 31,
    user_role: 'STUDENT',
    system_resource_id: 8,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 32,
    user_role: 'TEACHER',
    system_resource_id: 8,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // GRADES RESOURCE
  {
    id: 33,
    user_role: 'ADMIN',
    system_resource_id: 9,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 34,
    user_role: 'USER',
    system_resource_id: 9,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 35,
    user_role: 'STUDENT',
    system_resource_id: 9,
    can_create: false,
    can_read: true,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 36,
    user_role: 'TEACHER',
    system_resource_id: 9,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  // SYSTEM RESOURCES RESOURCE
  {
    id: 37,
    user_role: 'ADMIN',
    system_resource_id: 10,
    can_create: true,
    can_read: true,
    can_update: true,
    can_delete: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 38,
    user_role: 'USER',
    system_resource_id: 10,
    can_create: false,
    can_read: false,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 39,
    user_role: 'STUDENT',
    system_resource_id: 10,
    can_create: false,
    can_read: false,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 40,
    user_role: 'TEACHER',
    system_resource_id: 10,
    can_create: false,
    can_read: false,
    can_update: false,
    can_delete: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
